# Generated by Django 5.1.1 on 2024-10-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('index', models.IntegerField()),
                ('freq', models.FloatField()),
                ('question', models.TextField()),
                ('answer', models.IntegerField()),
                ('explanation', models.TextField()),
                ('reference', models.CharField(max_length=100)),
            ],
        ),
    ]
